index:
    path: /
    controller: App\Controller\ArticleController::homepage

show_new:
    path: /news/{slug}
    controller: App\Controller\ArticleController::show

article_togle_heart:
    path: /news/{slug}/heart
    methods: [POST]
    controller: App\Controller\ArticleController::toggleArticleHeart
